---
  - name: install docker on ubuntu servers
    import_tasks: ubuntu.yml
    when: ansible_facts.os_family | lower == "debian"

  - name: install docker on fedora servers
    import_tasks: fedora.yml
    when: ansible_facts.os_family | lower == "redhat"
       
