---
DOCKER_PACKAGES:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - lsb-release          
DOCKER_CE:
  - docker-ce
  - docker-ce-cli
  - containerd.io
DOCKER_COMPOSE_VERSION: "1.29.2"    
